### ISSUE TITLE
AppRun can't locate ld-linux.so.2

### ISSUE THREAD

**Issue by mssalvatore** [AppImageCrafters/appimage-builder#93]
I built an AppImage on Ubuntu Bionic 18.04.5 using appimage-builder. When I run my AppImage, I get this warning and error: 

```
APPRUN_WARNING: Unable to find interpreter: /lib/ld-linux.so.2
Unable to read file: /tmp/.mount_monkeyUQY0XT//opt/libc/lib/ld-linux.so.2
```

If I immediately run my image again, I get the same APPRUN_WARNING, but my application executes without issue. The image runs without showing the warning or error on the first try on the latest Kali. If I copy the image to another bionic machine, I get the warning and error again. Running on Ubuntu Focal results in an identical error on the first run, followed by a segfault on subsequent runs.

I've tried using strace to compare the execution, but I have yet to find an explanation for the behavior.

**Comment by azubieta** [comment]
`/lib/ld-linux.so.2` is the 32bits build of the ld tool. This means that your bundle contains 32 bits binaries and also requires a 32bits loader. If your system doesn't have such loader the `APPRUN_WARNING: Unable to find interpreter` error will be shown. On the other hand if your bundle doesn't include it the `Unable to read file: /tmp/.mount_monkeyUQY0XT//opt/libc/lib/ld-linux.so.2` is shown.

Building AppImages with mixed architectures is possible, you just have to choose one as main and make sure that the first binary you call (the one specified in the exec) also has this arch.

It would be great if you could share your AppImage or your recipe (if possible) so we can take a look at it. You can use http://transfer.sh/ to share it.

**Comment by mssalvatore** [comment]
I've attached the `recipe.yml`, a build  log, and the `.bundle.yml`. The upload to transfer.sh is going very slowly, but I'll provide a link when I have one.

[recipe_yml.txt](https://github.com/AppImageCrafters/appimage-builder/files/5998034/recipe_yml.txt)
[build_log.txt](https://github.com/AppImageCrafters/appimage-builder/files/5998035/build_log.txt)
[bundle_yml.txt](https://github.com/AppImageCrafters/appimage-builder/files/5998036/bundle_yml.txt)


I was able to find 3 32-bit binaries in the AppDir. They are:

```
usr/src/monkey_island/cc/binaries/monkey-linux-32
usr/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-32bit/run_d
usr/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-32bit/run
```

As far as I can tell, these files are not executed when the application starts. If I remove them from the AppDir and rebuild, the application starts without issue.

It appears that just the presence of these binaries in the AppDir causes the issue.

**Comment by azubieta** [comment]
From the build log, notice the warning: `WARNING:root:Required interpreter 'python' could not be found in the AppDir `
You would also like to include python (2) in your bundle.

If the issue are the 32 bits files then you would also have to embed `libc6:i386`. That should fix the issue

**Comment by mssalvatore** [comment]
Adding python2 removes those warnings, but doesn't fix the issue.

I added `libc6-i386`. It also does not solve the problem.

transfer.sh was not cooperating with me, so you can download the AppImage here: https://salvatoresecurity.com/monkey.AppImage

**Comment by azubieta** [comment]
It seems that for some reason it's not being deployed into the bundle. Try removing the ` [arch=amd64] ` from the sourcelines in order to allow both i386 and amd64 packages to be selected.

Could you share the log after adding `libc6-i386`?

**Comment by mssalvatore** [comment]
To clarify, the package at https://salvatoresecurity.com/monkey.AppImage does not include libc6-i386. Here's the build log with the `[arch=64]`removed:
[build_log_32.txt](https://github.com/AppImageCrafters/appimage-builder/files/6003133/build_log_32.txt)

I've verified that `lib/ld-linux.so.2` does exist in the appdir as a symlink to `../lib/ld-linux.so.2`

**Comment by azubieta** [comment]
First, always clear your build environment before running `appimage-builder` to avoid issues like this:
`WARNING:root:Required interpreter 'appimage-f5d659fa-db6f-4a84-b46b-8893153ca973-env' could not be found in the AppDir while processing /home/msalvatore/appimage/../monkey-appdir/usr/src/monkey_island/cc/ui/node_modules/.bin/ansi-html`

Second you will have to specify the `libc6:i386` explicitly in the apt include, otherwise it could be ignored. This should also be fixed in the tool.

**Comment by mssalvatore** [comment]
The issue seems to only occur when `usr/src/monkey_island/cc/binaries/monkey-linux-32` is present. This doesn't make a whole lot of sense to me. This binary does not get executed when the AppImage starts. Below are links to two tarballs. Each contains the following

1. a `build_log.txt` containing appimage-builder's build log with the log level set to debug
2. the `.bundle.yml` I found in the AppDir
3. the appimage-builder recipe `monkey_island_builder_yml.txt`
4. an strace file `trace.txt` to prove that `monkey-linux-32` does not get executed
5. the appimage built by appimage-builder

The *only* difference between these two builds is that in one, the `monkey-linux-32` file is present and in the other it is not. Between builds, I completely removed my AppDir, appimage-builder's cache, and the AppImage that was built.

http://salvatoresecurity.com/broken.tar.gz
http://salvatoresecurity.com/working.tar.gz


As a workaround, I:
1. Build the AppDir with appimage-builder and skip building the appimage (`--skip-appimage`)
1. Copy the 32-bit binary to the AppDir
1. Build the AppImage with appimage-builder from the already-built AppDir (`--skip-build`)

The package that is built from this process works consistently without issue. I've tested it on Ubuntu 18.04 and 20.04, Kali 2020.4, and CentOS 8.3.2011.

**Comment by azubieta** [comment]
The AppRun tries to copy `/tmp/.mount_monkeyUQY0XT//opt/libc/lib/ld-linux.so.2` to a fixed path in `/tmp` on startup. It fails as the file doesn't exist and an empty file is created. Next time it tries to start it founds a file in place an assumes it's  the right one and doesn't try to copy it.

I'm already working on seeing why the libc6:i386 is not being deployed as required.

For your workaround, you can use a section script https://appimage-builder.readthedocs.io/en/latest/reference/version_1.html#section-scripts and manually do the fixes until I get this fixed.

**Comment by mssalvatore** [comment]
Do we know why libc6:i386 is required?

**Comment by azubieta** [comment]
> Do we know why libc6:i386 is required?

It provides the missing files

**Comment by mssalvatore** [comment]
But why is AppRun looking for the 32-bit interpreter in the first place?

**Comment by azubieta** [comment]
If a 32bits binary is found in the bundle its interpreter is added to the required interpreters lists and the binary gets patched with a `/tmp` based path. This what we use to switch the interpreter at runtime. The AppRun makes sure to deploy the right interpreters the the expected paths at startup.

**Comment by azubieta** [comment]
@mssalvatore your issue should be fixed with #97 please reinstall appimage-builder from master an try again.

**Comment by mssalvatore** [comment]
Thanks! It's all working for me now.

**Comment by azubieta** [comment]
Good to know :)
